### ISSUE TITLE
Can I change the SDT2I base model for different style

### ISSUE THREAD

**Issue by qinziqiao** [Doubiiu/DynamiCrafter#39]
Great work!
I wonder if I can switch the base model during inference, such as some finetune models from SD1.5.
Is it compatible?

**Comment by Doubiiu** [comment]
Thanks for your interest!
I think it cannot be directly switched since other layers in this video model (e.g. temporal layers, image context projection module) are trained based on SDv2.1. It might require a lot of effort to switch that, which may involve further fine-tuning, thus I don't recommend that. You can fine-tune the spatial layers of this model based on your needs instead.
