### ISSUE TITLE
Inquiry about num_frames and GPU memory consumption

### ISSUE THREAD

**Issue by HyeonHo99** [Doubiiu/DynamiCrafter#9]
Hi, thank you for open-sourcing such a nice work!

For the generation of an video with 256x256, it is stated that 20GB gpu memory is required.
(1) I wonder how many frames are generated in the above case.
(2) If I reduce the number of frames to generate, then will it be possible to generate a video with bigger resolution than 256x256? Or the results will be not as good since the model is trained in the dataset of 256x256?

Thank you in advance :)

**Comment by Doubiiu** [comment]
Hi. Thanks for your interest!
(1) 16 frames.
(2) The animation results on higher-resolution images will be almost still since the original model is trained at 256x256.
We will release a higher-resolution & watermark-free & high-quality & more stable version of DynamiCrafter within this month (hopefully). Please stay tuned! I hope the community can help to reduce the memory consumption by using existing engineering advances of diffusion model, and I will also try that if I was available.

**Comment by eugenelyj** [comment]
@Doubiiu Hi, Is the released watermark-free model trained on datasets other than webvid?

**Comment by Doubiiu** [comment]
Hi @eugenelyj , yes, it was trained on a self-collected high-quality watermark-free video dataset.
